# Generated by Django 5.0.2 on 2024-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/posts/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
