# Generated by Django 5.0.2 on 2024-05-19 14:02

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='describtion',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='This Post hsnt any description', max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[post.models.image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
